### ISSUE TITLE
WaveVote project

### ISSUE THREAD

**Issue by descampsk** [stonecoldpat/anonymousvoting#15]
Hello,

I used your work as a basis for developing a more advanced application.
In particular, I created an application under Electron to allow a simple use of the vote.
Concerning the voting protocol:
- I deleted the limit of 40 voters;
- I added the possibility of a multi-candidate vote;
- I added a unique code authentication;
- I removed the obligation to vote, which decreases the strength of the secrecy of the vote (the secret is known by the administrator)
- I am creating a distributed administration which will guarantee the secrecy of the vote as long as all the administrators are not corrupt. It only takes one administrator who is not corrupted to keep all votes secret.

You can find this project here : https://github.com/descampsk/wavevote

Do not hesitate to comment.

Thank you again for your work.

**Comment by stonecoldpat** [comment]
This is really really really cool!

I'm going to be presenting at DevCon3 this year - I am 100% going to do a huge shout out for this project 💃 💃 💃 💃 💃 💃 

p.s.I still need to get back to you on the other issue. November i'll be able to dive back into this.
