### ISSUE TITLE
Open-source without a license ?

### ISSUE THREAD

**Issue by dlecan** [stonecoldpat/anonymousvoting#2]
From README:
> please play with this code! Do what you want! Completely open-source

Can you give more details on what is allowed to do or not with this code?

I didn't find any license in the repository, so the best would be to choose an open-source license to answer my question: https://choosealicense.com/ for example.

Thank you

**Comment by stonecoldpat** [comment]
I'll update the readme to reflect this (and parts of the code).

It will be the MIT license: 
https://choosealicense.com/licenses/mit/

**Comment by stonecoldpat** [comment]
> Can you give more details on what is allowed to do or not with this code?

I forgot to answer this part. You are free to do anything with this code. I suspect it will also be usable in RSK or any solidity supporting ledger.
