### ISSUE TITLE
Question: Is there something special about voters[1]?

### ISSUE THREAD

**Issue by SilentCicero** [stonecoldpat/anonymousvoting#9]
I'm trying to understand the reconstruction step, when voters register, why is account 1 being used in the way you specified here:

https://github.com/stonecoldpat/anonymousvoting/blob/master/AnonymousVoting.sol#L842

I'm having trouble on my end with your system. I'm using my JS conversion of the Java file and I'm trying to determine if there is something wrong with my JS version or if I'm not understanding accounts right.

What is odd is that all other voters (0, 2, 3) work fine (their ZKP is created and verified successfully, and they can create either the yes or no ZKP, and they verify out as well... accept account/voter[1]. The ZKP proof gets created and verified as normal, but when I try to create the 1 of 2 ZKP yes or no, I create it, it looks normal, but on the verify 1 of 2 step, I get in an invalid reading.

Any thoughts on this?

I'm sure its my JS or something..

**Comment by stonecoldpat** [comment]
Hi,

Let me explain what is going on first before talking about that code.

<img width="615" alt="screen shot 2017-06-23 at 09 38 50" src="https://user-images.githubusercontent.com/6450946/27473663-d80d9858-57f7-11e7-9b1e-656e3c27456c.png">

> It is worth highlighting that on the ellipitic curve multiplication becomes addition, and exponentiations become multiplication... so when I say "add" on the elliptic curve... it is multiplication in the above picture. 

lets pretend we are computing the reconstructed key for voter 3 (i.e. the robot). 

We add the voting keys for Voter 1 and Voter 2 together (i.e. PK_{12}, and we add the voting keys for voter 4 and voter 5 together (PK_{45}). 

Next, to compute the reconstructed key for voter 3.... we simply subtract both of the sums ReconstructedKey_{3} = PK_{12} - PK_{45}

Now.... there are two edge cases for both the first and last voter. 

For the first voter (voter 0) - no subtraction/division is required... their reconstructed key is simply the sum of all voting keys 1,...,n.  This is what we see in the below code: 

```
      // Step 1 is to compute the index 1 reconstructed key
      afteri[0] = voters[1].registeredkey[0];
      afteri[1] = voters[1].registeredkey[1];
      afteri[2] = 1;

      for(uint i=2; i<totalregistered; i++) {
         Secp256k1._addMixedM(afteri, voters[i].registeredkey);
      }

      ECCMath.toZ1(afteri,pp);
      voters[0].reconstructedkey[0] = afteri[0];
      voters[0].reconstructedkey[1] = pp - afteri[1];
```

Here, we initialise the variable afteri with the voting key of voter 1.... and then add each voter's voting key after that..... so it is the sum of all voting keys 1 to n. 

This is adding every voter's voting key except for voter 0. (i.e. the sum of all voting keys from 1,

I'm not too sure about the problem with voter 1.... you might not be fetching the correct reconstructed key from the smart contract for voter 1? You could try using the values using the java program and then that would identify it is a problem with how you are storing the random numbers? 

If you want - it might be easier to ask me on skype about this stuff. skype: podgey-kins 

p.s. I have some slides here that might explain the protocol step by step as well: 
https://www.dropbox.com/s/kubf6b9c1d73xx5/Purdue.pptx?dl=0

**Comment by SilentCicero** [comment]
Great explanation, I had some idea of this from the white paper, but didn't understand the math well enough.

I made a stateless version of the reconstruction key phase to better understand what is going on. Keys are submitted in halfs (because solidity cant intake or output uint[][2] arrays..).

This function returns the same keys as the other simulation, but just in a stateless way. Do you see anything in this function that looks odd? I've compared it closely with yours and it seems to preform identically.

I've checked all keys and they all compute out as valid public/private/random numbers and ethereum keys.

```
// Timer has expired - we want to start computing the reconstructed keys
  function computeVotersReconstructionKeys(uint[] votersRegisteredkey0, uint[] votersRegisteredkey1) public constant returns(uint[] votersReconstructKey0, uint[] votersReconstructKey1) {
      uint totalregistered = votersRegisteredkey0.length;
      uint[] memory votersReconstructKey0Temp = new uint[](totalregistered);
      uint[] memory votersReconstructKey1Temp = new uint[](totalregistered);

      // Make sure at least 3 people have signed up...
      if(votersRegisteredkey0.length < 3 || votersRegisteredkey0.length != votersRegisteredkey1.length) {
        throw;
      }

      uint[2] memory temp;
      uint[3] memory yG;
      uint[3] memory beforei;
      uint[3] memory afteri;
      uint[2] memory voterRegisteredkey;

      // Step 1 is to compute the index 1 reconstructed key
      afteri[0] = votersRegisteredkey0[1];
      afteri[1] = votersRegisteredkey1[1];
      afteri[2] = 1;

      for(uint i = 2; i < totalregistered; i++) {
        uint[2] memory voterRegisteredkeyI;
        voterRegisteredkeyI[0] = votersRegisteredkey0[i];
        voterRegisteredkeyI[1] = votersRegisteredkey1[i];

         Secp256k1._addMixedM(afteri, voterRegisteredkeyI);
      }


      ECCMath.toZ1(afteri, pp);
      votersReconstructKey0Temp[0] = afteri[0];
      votersReconstructKey1Temp[0] = pp - afteri[1];

      // Step 2 is to add to beforei, and subtract from afteri.
      for(i = 1; i < totalregistered; i++) {

        if(i == 1) {
          beforei[0] = votersRegisteredkey0[0];
          beforei[1] = votersRegisteredkey1[0];
          beforei[2] = 1;
        } else {
          voterRegisteredkey[0] = votersRegisteredkey0[i - 1];
          voterRegisteredkey[1] = votersRegisteredkey1[i - 1];

          Secp256k1._addMixedM(beforei, voterRegisteredkey);
        }

        // If we have reached the end... just store beforei
        // Otherwise, we need to compute a key.
        // Counting from 0 to n-1...
        if(i == (totalregistered - 1)) {
          ECCMath.toZ1(beforei, pp);
          votersReconstructKey0Temp[i] = beforei[0];
          votersReconstructKey1Temp[i] = beforei[1];
        } else {

          // Subtract 'i' from afteri
          temp[0] = votersReconstructKey0Temp[i];
          temp[1] = pp - votersReconstructKey1Temp[i];

          // Grab negation of afteri (did not seem to work with Jacob co-ordinates)
          Secp256k1._addMixedM(afteri, temp);
          ECCMath.toZ1(afteri, pp);

          temp[0] = afteri[0];
          temp[1] = pp - afteri[1];

          // Now we do beforei - afteri...
          yG = Secp256k1._addMixed(beforei, temp);

          ECCMath.toZ1(yG, pp);

          votersReconstructKey0Temp[i] = yG[0];
          votersReconstructKey1Temp[i] = yG[1];
        }
      }

     votersReconstructKey0 = votersReconstructKey0Temp;
     votersReconstructKey1 = votersReconstructKey1Temp;
  }
```

**Comment by SilentCicero** [comment]
Side note, everyday I learn more about Sepc256k1/elliptic curve I am every more astonished humans have discovered/can use it's power.

**Comment by SilentCicero** [comment]
Got it! Just had a few bugs in my JS code. Thanks so much! Lets chat soon.
